### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by otymartin** [chbo297/CCZoomTransition#4]
@chbo297 
I found that this line causes a retain cycle where my presented view controller is never deinitialized.
  `var presentationController : CCSwipBackPresentationController? = nil`

creating a weak reference is what solved the problem.
`weak var presentationController : CCSwipBackPresentationController? = nil`

**Comment by aelam** [comment]
Same problem here!

**Comment by mikengyn** [comment]
Doing this prevents swipe dismissing from working

**Comment by otymartin** [comment]
@mikengyn good question let me check and find out because my swipe to dismiss doesnt work

**Comment by mikengyn** [comment]
@otymartin you can get rid of the strong reference and get the dismissal by swiping working by replacing this method. 

```
 func presentationController(forPresented presented: UIViewController, presenting: UIViewController?, source: UIViewController) -> UIPresentationController? {
        let pc = CCSwipBackPresentationController.init(presentedViewController: presented, presenting: presenting)
        self.presentationController = pc
        return pc
    } 
```

**Comment by otymartin** [comment]
@mikengyn hey i just tried this buy no luck :( it doesnt swipe back

**Comment by mikengyn** [comment]
@otymartin you also need to undo the original change you made. Which was adding the `weak` to `presentationController.`

**Comment by otymartin** [comment]
@mikengyn im doing an iPhoneX UI update now. One thing i failed to mention is my VC is not in a navigation controller. Could that be a cause? I intend to use UINavigationController in my UI Update.

**Comment by chbo297** [comment]
0.1.2 fixed
